Dev
Bivis63/Playlist_Maker pull request #3
Opened 2023-04-03 23:15 UTC by Bivis63

2023-04-04 22:50 UTC, NoDopezzz approved these changes

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +        } else {
⏫ Для простоты можно воспользоваться методом `orEmpty()`, которая вернет "", если значение равно null:
```
savedInstanceState?.getString(SAVED_DATA).orEmpty()
```

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            historyAdapter.tracksList=searchHistory.load()
⏫ Для изменения видимости элемента на экране можно использовать `extension` `View.isVisible`:

- `View.isVisible = true` соответствует `View.visibility = View.VISIBLE`
- `View.isVisible = false` соответствует `View.visibility = View.GONE`

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +    private fun clearButtonVisibility(s: CharSequence?): Int {
⏫ Так как метод `clearButtonVisibility` и `hideKeyboard` используются только в `SearchActivity`, то их стоит сделать приватными методами внутри этого класса. Статические методы - методы, для вызова которых не требуется объект класса - занимают память в процессе всей жизни приложения

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +        searchHistory.save()
⏫ Так как вызов метода `save()` всегда должен сопровождаться вызовом метода `addTrack`, то логику сохранения вызывать в самом `addTrack`

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    var searchHistoryList = ArrayList<Track>()
⏫ Поле `searchHistoryList` можно сделать `private`,  т.к. оно используется только в `SearchHistory`

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +        if (searchHistoryList.size < 10) {
⏫ Данную структуру можно разложить на 3 не вложенных ответвления:
- `trackIndex == -1`, значит трек уже существует, значит вызываем `replacingDuplicateElement`
- `searchHistoryList.size < 10`, значит 10 еще не достигли, поэтому просто добавляем в начало новый трек
- `searchHistoryList.size >= 10`, значит 10 в истории уже есть, поэтому перед добавлением нового трека нужно сначала удалить первый

Можно реализовать такие проверки с помощью котлиновской конструкции `when`. В таком случае такой код будет менее вложенным и более удобочитаемым

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    fun replacingDuplicateElement(index: Int) {
⏫ Метод `replacingDuplicateElement` может быть `private`

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchHistory.kt
> +    fun ClearSearchHistoryList() {
⏫ Лучше придерживаться общепринятого нейминга методов camelCase'ом с маленькой буквы

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
> +            }else
⏫ Лишняя проверка на `checked` получается. Мы можем сразу изменять настройки в префах, а потом вызывать switchTheme у App

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
> +    val switch = App()
⏫ Не стоит создавать переменную `App`, за это ответственна Android-система. Чтобы получить экземпляр текущего приложения стоит вызвать `applicationContext as App`, как это сделано при нажатии на тогл

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SettingsActivity.kt
> +        switch.switchTheme(replacement)
⏫ Нет необходимости менять тему при создании `SettingsActivity`, т.к. тема применяется при создании `App`. Тема распространяется на все приложение, а значит и на все его `Activity`

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/TrackAdapter.kt
> +//            tracksList.removeAt(position)
⏫ Если хочется удалять трек при нажатии, стоит передать событие о нажатии наружу - в `Activity`. `Activity` же должна изменить текущий список в `TrackAdapter` и переназначить переменную `tracksList`.

Но текущее задание этого функционала не требует, так что если есть желание, то можешь поэкспериментировать в отдельной ветке

2023-04-04 22:50 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/TracksDiffCallBack.kt
> +class TracksDiffCallBack(
👍 Крутая идея добавить `DiffUtils`!

⏫ Обрати внимание, что при применении `DiffUtils` не нужно применять `notify*` методы у адаптера, т.к. они будут применены автоматически

2023-04-04 22:52 UTC, NoDopezzz requested changes

2023-04-04 22:52 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            binding.searchHistory.visibility = if (hasFocus && binding.inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
⚠️ Стоит также добавить условие непустой истории поиска, как это требует задание

2023-04-05 19:06 UTC, Bivis63 commented on app/src/main/java/com/example/playlistmaker/TracksDiffCallBack.kt
> +class TracksDiffCallBack(
в поиске все работает , в истории пока не разобрался почему не получаеться , пришлось использовать notify*

2023-04-05 19:07 UTC, Bivis63 commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            binding.searchHistory.visibility = if (hasFocus && binding.inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
реализовал через метод checkList  при вызове в onCreate потерпел неудачу при повороте экрана , вызвал его в onResume

2023-04-06 19:31 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/TracksDiffCallBack.kt
> +class TracksDiffCallBack(
Дело в том, что список истории треков меняется с помощью переназначения переменной списка, а изменением состава списка. Если просто менять состав списка с помощью методов `add` или `remove`, то делегат-метод `set(value)` вызываться не будет, а значит и `DiffUtils` не будут задействованы

2023-04-06 19:41 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            binding.searchHistory.visibility = if (hasFocus && binding.inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
⚠️ В таком случае, если ввести в поиск список треков, а затем свернуть и снова открыть приложение, будет вызван метод `checkList()`. И в случае, если в истории есть треки, они будут отображены на экране, даже если до этого были отображены найденные треки.
В твоем случае было бы достаточно добавить следующую проверку в методе `onTextChanged`:
```
val searchHistoryTrackList = searchHistory.load()
binding.searchHistory.visibility =  if (binding.inputEditText.hasFocus() && s?.isEmpty() == true && searchHistoryTrackList.isNotEmpty()) View.VISIBLE else View.GONE
historyAdapter.tracksList = searchHistory.load()
```

2023-04-06 20:48 UTC, Bivis63 commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            binding.searchHistory.visibility = if (hasFocus && binding.inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
я когда захожу в "Поиск" у меня edittext не в фокусе ,эта проверка не будет работать пока я в фокус не возьму edittext и у меня так же история поиска не будет отображаться без фокуса

2023-04-08 12:52 UTC, Bivis63 commented on app/src/main/java/com/example/playlistmaker/SearchActivity.kt
> +            binding.searchHistory.visibility = if (hasFocus && binding.inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
добавил проверку в onResume все заработало как нужно , пробывал добавит проверку как вы мне подсказали, но если checklist вызывать в onCreate , то при повороле экрана все исчезает

2023-04-09 12:42 UTC, NoDopezzz approved these changes

2023-04-09 14:37 UTC, merged